[package]
name = "node"
version = "0.1.0"
edition = "2021"

[dependencies]
net_interface.workspace = true

futures.workspace = true
bytes.workspace = true
bollard.workspace = true
tokio.workspace = true
tonic.workspace = true
serde.workspace = true

serde_yaml = { version = "0.9.34" }
